<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.*" />
    <PackageReference Include="Handlebars.Net" Version="2.*" />
    <PackageReference Include="JsonPath.Net" Version="1.*" />
    <PackageReference Include="YamlHttpClient" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OAM.Domain\OAM.Domain.csproj" />
    <ProjectReference Include="..\OAM.Infrastructure\OAM.Infrastructure.csproj" />
  </ItemGroup>

</Project>
